# -*- coding: utf-8 -*-
"""Predecir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfwm7Ed5v9xsjypdkZXO8d6MUichdASa
"""

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

longitud, altura = 100, 100
modelo = '/content/gdrive/My Drive/Machine Learning/Clasificador/modelo/modelo_Fl.h5'
pesos = '/content/gdrive/My Drive/Machine Learning/Clasificador/modelo/pesos_Fl.h5'

cnn = load_model(modelo)
cnn.load_weights(pesos)

def predecir(file):
  x = load_img(file, target_size=(longitud, altura))
  x = img_to_array(x)
  x = np.expand_dims(x, axis=0)
  arreglo = cnn.predict(x)
  resultado = arreglo[0]
  respuesta = np.argmax(resultado)
  if respuesta == 0:
    print("daisy")
  elif respuesta == 1:
    print("dandelion")
  elif respuesta == 2:
    print("rose")
  elif respuesta == 3:
    print("sunflower")
  elif respuesta == 4:
    print("tulip")
  else:
    print("No se reconocio la imagen")
    return respuesta

imagen_flor = '/content/gdrive/My Drive/Machine Learning/Clasificador/data/flowers/data/imagenes_nuevas/daisy_flower.jpg'

predecir(imagen_flor)

img=mpimg.imread(imagen_flor)

plt.imshow(img)